name: Pull Request Build

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: write
  pull-requests: write

jobs:
  fetch-latest-ipa:
    name: Get latest ipa
    runs-on: ubuntu-latest
    outputs:
      ipa_url: ${{ steps.get-latest-ipa.outputs.ipa_url }}
    steps:
      - name: Get latest Discord ipa
        id: get-latest-ipa
        run: |
          RESPONSE=$(curl -s -H "Accept: application/json" https://ipa.aspy.dev/discord/stable/)
          LATEST_IPA=$(echo $RESPONSE | jq -r '.[-1].url' | sed 's/^\.\///')
          FULL_URL="https://ipa.aspy.dev/discord/stable/$LATEST_IPA"
          echo "ipa_url=$FULL_URL" >> $GITHUB_OUTPUT

  build:
    name: Build Unbound
    needs: fetch-latest-ipa
    uses: ./.github/workflows/build.yml
    with:
      ipa_url: ${{ needs.fetch-latest-ipa.outputs.ipa_url }}
      release: false
      caller_workflow: "ci"
    secrets: inherit

  comment-pr:
    name: Comment on PR
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 1

      - name: Get commit info
        id: commit-info
        run: |
          # Get PR commit info
          COMMIT_HASH=$(git rev-parse --short HEAD)
          COMMIT_MESSAGE=$(git log -1 --pretty=%B | tr -d '\n')
          COMMIT_TIME=$(date "+%Y-%m-%d %H:%M:%S")
          
          echo "hash=$COMMIT_HASH" >> $GITHUB_OUTPUT
          echo "message=$COMMIT_MESSAGE" >> $GITHUB_OUTPUT
          echo "time=$COMMIT_TIME" >> $GITHUB_OUTPUT

      - name: Comment on current PR
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            ### Build for #${{ github.event.pull_request.number }}

            **Commit**: [#${{ steps.commit-info.outputs.hash }}](https://github.com/${{ github.repository }}/commit/${{ github.event.pull_request.head.sha }}) `${{ steps.commit-info.outputs.message }}`
            **Build Time**: ${{ steps.commit-info.outputs.time }}
            
            #### Artifacts:
            - [**${{ needs.build.outputs.deb_filename }}**](${{ needs.build.outputs.deb_url }})
            - [**${{ needs.build.outputs.ipa_filename }}**](${{ needs.build.outputs.ipa_url }})

            <sub>This comment was automatically generated. [View workflow run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})</sub>
          comment-tag: build-result
          github-token: ${{ secrets.GITHUB_TOKEN }}